export default [{
    count: 0,
    id: 1,
    level: 1,
    name: "快餐便当",
    sub_categories: [{
        count: 0,
        id: 2,
        level: 2,
        name: "简餐"
    }, {
        count: 0,
        id: 3,
        level: 2,
        name: "盖浇饭"
    }, {
        count: 0,
        id: 4,
        level: 2,
        name: "米粉面馆"
    }, {
        count: 0,
        id: 5,
        level: 2,
        name: "包子粥店"
    }, {
        count: 0,
        id: 6,
        level: 2,
        name: "香锅砂锅"
    }, {
        count: 0,
        id: 7,
        level: 2,
        name: "麻辣烫"
    }, {
        count: 0,
        id: 8,
        level: 2,
        name: "饺子馄饨"
    }, {
        count: 0,
        id: 9,
        level: 2,
        name: "汉堡"
    }, {
        count: 0,
        id: 10,
        level: 2,
        name: "生煎锅贴"
    }, {
        count: 0,
        id: 11,
        level: 2,
        name: "黄焖鸡米饭"
    }, {
        count: 0,
        id: 12,
        level: 2,
        name: "烧腊饭"
    }, {
        count: 0,
        id: 13,
        level: 2,
        name: "煲仔饭"
    }, {
        count: 0,
        id: 14,
        level: 2,
        name: "咖喱饭"
    }]
}, {
    count: 0,
    id: 2,
    level: 1,
    name: "特色菜系",
    sub_categories: [{
        count: 0,
        id: 16,
        level: 2,
        name: "川湘菜"
    }, {
        count: 0,
        id: 17,
        level: 2,
        name: "其他菜系"
    }, {
        count: 0,
        id: 18,
        level: 2,
        name: "江浙菜"
    }, {
        count: 0,
        id: 19,
        level: 2,
        name: "粤菜"
    }, {
        count: 0,
        id: 20,
        level: 2,
        name: "海鲜"
    }, {
        count: 0,
        id: 21,
        level: 2,
        name: "火锅烤鱼"
    }, {
        count: 0,
        id: 22,
        level: 2,
        name: "东北菜"
    }, {
        count: 0,
        id: 23,
        level: 2,
        name: "西北菜"
    }, {
        count: 0,
        id: 24,
        level: 2,
        name: "云南菜"
    }, {
        count: 0,
        id: 25,
        level: 2,
        name: "新疆菜"
    }, {
        count: 0,
        id: 26,
        level: 2,
        name: "鲁菜"
    }]
}, {
    count: 0,
    id: 3,
    level: 1,
    name: "异国料理",
    sub_categories: [{
        count: 0,
        id: 27,
        level: 2,
        name: "日韩料理"
    }, {
        count: 0,
        id: 28,
        level: 2,
        name: "西餐"
    }, {
        count: 0,
        id: 29,
        level: 2,
        name: "披萨意面"
    }, {
        count: 0,
        id: 30,
        level: 2,
        name: "东南亚菜"
    }]
}, {
    count: 0,
    id: 4,
    level: 1,
    name: "小吃夜宵",
    sub_categories: [{
        count: 0,
        id: 31,
        level: 2,
        name: "小龙虾"
    }, {
        count: 0,
        id: 32,
        level: 2,
        name: "地方小吃"
    }, {
        count: 0,
        id: 33,
        level: 2,
        name: "烧烤"
    }, {
        count: 0,
        id: 34,
        level: 2,
        name: "炸鸡炸串"
    }, {
        count: 0,
        id: 35,
        level: 2,
        name: "鸭脖卤味"
    }, {
        count: 0,
        id: 36,
        level: 2,
        name: "零食"
    }]
}, {
    count: 0,
    id: 5,
    level: 1,
    name: "甜品饮品",
    sub_categories: [{
        count: 0,
        id: 37,
        level: 2,
        name: "奶茶果汁"
    }, {
        count: 0,
        id: 38,
        level: 2,
        name: "甜品"
    }, {
        count: 0,
        id: 39,
        level: 2,
        name: "咖啡"
    }]
}, {
    count: 0,
    id: 6,
    level: 1,
    name: "果蔬生鲜",
    sub_categories: [{
        count: 0,
        id: 40,
        level: 2,
        name: "水果"
    }, {
        count: 0,
        id: 41,
        level: 2,
        name: "生鲜"
    }, {
        count: 0,
        id: 42,
        level: 2,
        name: "蔬菜"
    }, {
        count: 0,
        id: 43,
        level: 2,
        name: "海鲜水产"
    }]
}, {
    count: 0,
    id: 7,
    level: 1,
    name: "鲜花蛋糕",
    sub_categories: [{
        count: 0,
        id: 44,
        level: 2,
        name: "鲜花"
    }, {
        count: 0,
        id: 45,
        level: 2,
        name: "蛋糕"
    }, {
        count: 0,
        id: 46,
        level: 2,
        name: "面包"
    }]
}, {
    count: 0,
    id: 8,
    level: 1,
    name: "商店超市",
    sub_categories: [{
        count: 0,
        id: 47,
        level: 2,
        name: "超市"
    }, {
        count: 0,
        id: 48,
        level: 2,
        name: "便利店"
    }, {
        count: 0,
        id: 49,
        level: 2,
        name: "名酒坊"
    }, {
        count: 0,
        id: 50,
        level: 2,
        name: "零食饮料"
    }, {
        count: 0,
        id: 51,
        level: 2,
        name: "水站"
    }, {
        count: 0,
        id: 52,
        level: 2,
        name: "茶"
    }, {
        count: 0,
        id: 53,
        level: 2,
        name: "奶站"
    }, {
        count: 0,
        id: 54,
        level: 2,
        name: "粮油"
    }, {
        count: 0,
        id: 55,
        level: 2,
        name: "美妆母婴"
    }]
}]
